# Generated by Django 4.2 on 2023-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-time_register']},
        ),
        migrations.AlterField(
            model_name='scan',
            name='time_register',
            field=models.DateTimeField(auto_now=True, db_column='timestamp'),
        ),
    ]
